// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-vWyEIkAPeXiXg_NWgiIVQGHr7cje0Ss',
    appId: '1:273141509959:web:56dd56075738b255912662',
    messagingSenderId: '273141509959',
    projectId: 'simple-mobile-app-9214b',
    authDomain: 'simple-mobile-app-9214b.firebaseapp.com',
    storageBucket: 'simple-mobile-app-9214b.appspot.com',
    measurementId: 'G-2EQQCJRBLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPW_C7WvRib2v9Ca42GpUshThetplRDko',
    appId: '1:273141509959:android:1279c8991af629d6912662',
    messagingSenderId: '273141509959',
    projectId: 'simple-mobile-app-9214b',
    storageBucket: 'simple-mobile-app-9214b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNP90SF8rORN1829Ew1YNHZU_8KOezGvg',
    appId: '1:273141509959:ios:84fc459afead06d6912662',
    messagingSenderId: '273141509959',
    projectId: 'simple-mobile-app-9214b',
    storageBucket: 'simple-mobile-app-9214b.appspot.com',
    iosBundleId: 'com.example.simpleFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNP90SF8rORN1829Ew1YNHZU_8KOezGvg',
    appId: '1:273141509959:ios:0728aaafa7ff059d912662',
    messagingSenderId: '273141509959',
    projectId: 'simple-mobile-app-9214b',
    storageBucket: 'simple-mobile-app-9214b.appspot.com',
    iosBundleId: 'com.example.simpleFlutterApp.RunnerTests',
  );
}
